version: '3'

services:
  labelimg:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    user: $DOCKER_USER
    environment:
      - DISPLAY=${DISPLAY}
      - NUMBA_CACHE_DIR=/tmp
      - PS1=\e[32m\u@\h \e[35m \e[34m\w\n\e[0m> 
    volumes:
      - ../:/labelimg/
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/video0:/dev/video0"
